### ISSUE TITLE
The homepage is dead

### ISSUE THREAD

**Issue by sskras** [Tostis/areca#2]
Seems like `areca-backup.org` domain name has expired.

**Comment by StatusCode404** [comment]
RIP Areca!  I've moved on to Duplicacy CLI open source version.

**Comment by sskras** [comment]
Thanks for the status update. Should this Github project archived then?
So the people knows the status in advance :)

**Comment by StatusCode404** [comment]
That's a question for @Tostis 
I think it is fine as is.  Still works but no active improvement nor evolution.  No active development for example to use the latest and greatest from the latest JAVA LTS versions, etc.

**Comment by Tostis** [comment]
I'm not the author of this software and I'm not involved with Oliver Petrucci. You can browser [here](https://web.archive.org/web/20230329033205/http://www.areca-backup.org/) the latest snapshot of the official site.
I have not time to develop this software but I currently use it in production.
This repository is easier to build so you can fork and enhance it.
